// GAME ACTIONS CONSTANTS
export const GAME_START_CONGIGURATION: string = 'GAME_START_CONGIGURATION';
export const CONFIGURE_GAME_AFTER_CORRECT_ANSWER =
   'CONFIGURE_GAME_AFTER_CORRECT_ANSWER';
export const CONFIGURE_GAME_AFTER_INCORRECT_ANSWER =
   'CONFIGURE_GAME_AFTER_INCORRECT_ANSWER';
export const CONFIGURE_GAME_AFTER_INCORRECT_ANSWER_ON_1_LEVEL =
   'CONFIGURE_GAME_AFTER_INCORRECT_ANSWER_ON_1_LEVEL';
export const GAME_OVER = 'GAME_OVER';

// USER ACTIONS CONTANTS
export const USER_PICKED_DIGIT: string = 'USER_PICKED_DIGIT';
export const CHANGE_LEVEL: string = 'CHANGE_LEVEL';
export const CHANGE_USER_SCORE: string = 'CHANGE_USER_SCORE';
export const TOOGLE_IS_USER_CAN_TYPE = 'TOOGLE_IS_USER_CAN_TYPE';
export const USER_RESPONDED_CORRECT = 'USER_RESPONDED_CORRECT';
export const USER_RESPONDED_INCORRECT = 'USER_RESPONDED_INCORRECT';
export const USER_RESPONDED_INCORRECT_ON_1_LEVEL =
   'USER_RESPONDED_INCORRECT_ON_1_LEVEL';
export const USER_LOST_GAME = 'USER_LOST_GAME';
export const RESET_USER_STATS = 'RESET_USER_STATS';
