// GAME ACTIONS CONSTANTS
export const DRAWN_NEW_DIGITS: string = 'DRAWN_NEW_DIGITS';
export const CONFIGURE_GAME_AFTER_CORRECT_ANSWER =
   'CONFIGURE_GAME_AFTER_CORRECT_ANSWER';

// USER ACTIONS CONTANTS
export const USER_PICKED_DIGIT: string = 'USER_PICKED_DIGIT';
export const CHANGE_LEVEL: string = 'CHANGE_LEVEL';
export const CHANGE_USER_SCORE: string = 'CHANGE_USER_SCORE';
export const TOOGLE_IS_USER_CAN_TYPE = 'TOOGLE_IS_USER_CAN_TYPE';
export const USER_RESPONDED_CORRECT = 'USER_RESPONDED_CORRECT';
